### ISSUE TITLE
Support for Azure Workload Identity

### ISSUE THREAD

**Issue by aji-sri** [webdevops/azure-keyvault-exporter#4]
Would be nice to have support for access through AZ Workload Identity

**Comment by mblaschke** [comment]
implemented with `23.5.0-beta0`, preparing releases (also for all other exporters)

**Comment by aji-sri** [comment]
@mblaschke Have used the tag version and tested the solution, works perfectly fine. Thank you.

Any ETA on the release?

**Comment by mblaschke** [comment]
`23.6.0` released, sorry for the delay
