### ISSUE TITLE
Filter KeyVaults by Tags / Kusto Query

### ISSUE THREAD

**Issue by jkroepke** [webdevops/azure-keyvault-exporter#5]
Hi there, 

I would like to know, if its possible to implement to filter KeyVaults by tag?

Some of our KeyVault are having network restrictions and I would like to exclude them from monitoring to avoid errors.

Similiar to the fliter param on the `/probe/metrics/resourcegraph` from azure-metrics-exporter.

**Comment by mblaschke** [comment]
resourceGraph or `$filter` support?
the last one is easier to implement but doesn't offer all possibilities what resourceGraph offers 🤔

**Comment by jkroepke** [comment]
The `$filter` option seems sufficient, since it suppers filter by tag values. I may have the same request for azure-loganalytics-exporter, too.

**Comment by mblaschke** [comment]
you cannot have complex filters :(
so you cannot filter by resourceGroup AND tag

**Comment by jkroepke** [comment]
Its fine-ish for me. I would use a tag for opt-in monitoring and `$filter=tagName eq 'tag1' and tagValue eq 'Value1'` i documented that it works

**Comment by jkroepke** [comment]
I was looked at the Azure Portal, how the resource filter is implemented on the resource list. It seems like that the Azure Portal is using `https://management.azure.com/providers/Microsoft.ResourceGraph/resources?api-version=2021-03-01` here.
