### ISSUE TITLE
Tags in Metrics

### ISSUE THREAD

**Issue by aji-sri** [webdevops/azure-keyvault-exporter#6]
Hi ,

Would like to know, if it is possible to scrape **tags** as well which are added to Key | Secrets | Certificates level.

As we need to identity certain attributes while triggering any alerts from Prometheus

**Comment by mblaschke** [comment]
isn't it not enough to have these tag labels for `azurerm_keyvault_info` and then just join them in the query?

**Comment by aji-sri** [comment]
`azurerm_keyvault_info` is capturing Key Vault Level details, this won't be enough for us as our
Idea is, when we add any new secret to key vault, we add some _group_name_ tag.
This tag is at secret level, not at key vault level. And based on any alert condition, this tag would be use to identify, which specific team/group needs to be notified.

**Comment by aji-sri** [comment]
Hi @mblaschke ,

Thank you for the quick update, but I am not able to find the tags provided in secrets in prometheus. The current solution I assume injects tags but not retrieving the tags from Key Vault Secret | Key | Certificates

Steps to replicate,

1. Create a key vault "test-kv"
2. Create a secret "test-secret" within key vault with a tag as below
![image](https://github.com/webdevops/azure-keyvault-exporter/assets/117151358/dd197327-ff61-4306-90b9-9190bd03da27)

![image](https://github.com/webdevops/azure-keyvault-exporter/assets/117151358/b3c2b147-7943-4133-ab0c-68b2bab7cbd0)

Would be nice to see this tag in Prometheus.

**Comment by mblaschke** [comment]
for the current solution you have to set ` --keyvault.content.tag= ` (or env `$KEYVAULT_CONTENT_TAG`) for every tag you want to have exported.

eg `KEYVAULT_CONTENT_TAG=support-assigned-group tag1 tag 2 tag3` 
or ` --keyvault.content.tag=tag1  --keyvault.content.tag=tag2  --keyvault.content.tag=tag3`

does this fit?

**Comment by aji-sri** [comment]
@mblaschke this does work and fits for me.

thanks alot for quick response and enhancement on this
